//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLRapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldTripChoice
    {
        public int FieldTripChoiceId { get; set; }
        public Nullable<int> FieldTripOptionId { get; set; }
        public int RegistrationId { get; set; }
        public Nullable<int> FieldTripOptionId2 { get; set; }
        public Nullable<int> FieldTripOptionId3 { get; set; }
        public Nullable<int> FieldTripId { get; set; }
        public Nullable<bool> RecordDeleted { get; set; }
        public Nullable<int> FieldTripAllocated { get; set; }
    
        public virtual FieldTrip FieldTrip { get; set; }
        public virtual Registration Registration { get; set; }
        public virtual FieldTripOption FieldTripOption { get; set; }
        public virtual FieldTripOption FieldTripOption1 { get; set; }
        public virtual FieldTripOption FieldTripOption2 { get; set; }
        public virtual FieldTripOption FieldTripOption3 { get; set; }
    }
}
