//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLRapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class HonourContactLink
    {
        public Nullable<int> HonourId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public int HonourContactLinkId { get; set; }
        public Nullable<bool> RecordDeleted { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Honour Honour { get; set; }
    }
}
